### ISSUE TITLE
Mogelijkheid om vanuit claim alle objects aan te maken (contact, bedrijf, taak etc)

### ISSUE THREAD

**Issue by jwijnen** [CuppaCode/asp-portaal#80]
In de claim edit/create moet het mogelijk worden om alles in 1x aan te maken. Denk aan voertuigen functie + live search zodat je niet database vervuilt met al eerder gecreëerde objecten.

Hou ook rekening met dat alleen bedrijfs gerelateerde resultaten getoond moeten worden en dus niet contacten van bedrijf a en bedrijf x door elkaar.

**Comment by GeneralOrange** [comment]
Tested
