### ISSUE TITLE
Vereiste velden bij sluiten claim (met name financiële gegevens)

### ISSUE THREAD

**Issue by jwijnen** [CuppaCode/asp-portaal#94]
**Gesloten**
* Schade kosten
* Herstel kosten
* Soort schade

**Claim afgewezen**
* dropdown toevoegen voor reden van sluiting (verplicht bij status claim afgewezen)

**Comment by GeneralOrange** [comment]
Staat nu in PR, dus nog niet in development branch..

**Comment by GeneralOrange** [comment]
staat nu wel in dev branch
